package com.dcos.platform.certapi.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.dcos.platform.certapi.domain.ProcessedCompletion;
import com.dcos.platform.certapi.support.RequiresTestDatabase;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("test")
@RequiresTestDatabase
@DisplayName("ProcessedCompletionRepository tests")
class ProcessedCompletionRepositoryTest {

    @Autowired private ProcessedCompletionRepository repository;

    @Test
    @DisplayName("save and retrieve processed completion")
    void saveAndRetrieve() {
        String eventId = UUID.randomUUID().toString();
        UUID certificateId = UUID.randomUUID();

        ProcessedCompletion completion = new ProcessedCompletion();
        completion.setEventId(eventId);
        completion.setCertificateId(certificateId);

        repository.save(completion);

        Optional<ProcessedCompletion> retrieved = repository.findById(eventId);
        assertThat(retrieved)
                .isPresent()
                .get()
                .satisfies(
                        c -> {
                            assertThat(c.getEventId()).isEqualTo(eventId);
                            assertThat(c.getCertificateId()).isEqualTo(certificateId);
                            assertThat(c.getProcessedAt()).isNotNull();
                        });
    }

    @Test
    @DisplayName("event id with retry suffix can be stored")
    void retryEventIdStored() {
        String originalId = UUID.randomUUID().toString();
        String retryEventId = originalId + ":retry:1";
        UUID certificateId = UUID.randomUUID();

        ProcessedCompletion completion = new ProcessedCompletion();
        completion.setEventId(retryEventId);
        completion.setCertificateId(certificateId);

        repository.save(completion);

        Optional<ProcessedCompletion> retrieved = repository.findById(retryEventId);
        assertThat(retrieved)
                .isPresent()
                .get()
                .satisfies(c -> assertThat(c.getEventId()).isEqualTo(retryEventId));
    }

    @Test
    @DisplayName("processedAt timestamp is auto-generated")
    void processedAtAutoGenerated() {
        ProcessedCompletion completion = new ProcessedCompletion();
        completion.setEventId(UUID.randomUUID().toString());
        completion.setCertificateId(UUID.randomUUID());

        repository.save(completion);

        ProcessedCompletion retrieved = repository.findById(completion.getEventId()).get();
        assertThat(retrieved.getProcessedAt()).isNotNull();
        assertThat(retrieved.getProcessedAt()).isBeforeOrEqualTo(java.time.Instant.now());
    }

    @Test
    @DisplayName("duplicate event id throws DataIntegrityViolationException")
    void duplicateEventIdThrows() {
        String eventId = UUID.randomUUID().toString();
        UUID certificateId = UUID.randomUUID();

        // Save first completion
        ProcessedCompletion first = new ProcessedCompletion();
        first.setEventId(eventId);
        first.setCertificateId(certificateId);
        repository.save(first);

        // Attempt to save duplicate with same event id
        ProcessedCompletion duplicate = new ProcessedCompletion();
        duplicate.setEventId(eventId);
        duplicate.setCertificateId(UUID.randomUUID()); // Different cert, same event id

        assertThatThrownBy(() -> repository.save(duplicate))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("insertIfAbsent inserts a new row and returns 1")
    void insertIfAbsentInsertsNewRow() {
        String eventId = UUID.randomUUID().toString();
        UUID certificateId = UUID.randomUUID();

        int inserted = repository.insertIfAbsent(eventId, certificateId);

        assertThat(inserted).isEqualTo(1);
        Optional<ProcessedCompletion> retrieved = repository.findById(eventId);
        assertThat(retrieved)
                .isPresent()
                .get()
                .satisfies(c -> assertThat(c.getCertificateId()).isEqualTo(certificateId));
    }

    @Test
    @DisplayName("insertIfAbsent returns 0 for a duplicate event id without throwing")
    void insertIfAbsentReturnsZeroForDuplicate() {
        String eventId = UUID.randomUUID().toString();
        UUID certificateId = UUID.randomUUID();

        int firstInsert = repository.insertIfAbsent(eventId, certificateId);
        int duplicateInsert = repository.insertIfAbsent(eventId, UUID.randomUUID());

        assertThat(firstInsert).isEqualTo(1);
        assertThat(duplicateInsert).isEqualTo(0);
        // Original certificateId is preserved; the conflicting insert changed nothing.
        Optional<ProcessedCompletion> retrieved = repository.findById(eventId);
        assertThat(retrieved)
                .isPresent()
                .get()
                .satisfies(c -> assertThat(c.getCertificateId()).isEqualTo(certificateId));
    }
}
